name: meta_portrait_base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_0
  - libgomp=11.2.0=h1234567_0
  - libstdcxx-ng=11.2.0=h1234567_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1o=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cachetools==5.2.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - easydict==1.9
    - entrypoints==0.4
    - fastjsonschema==2.15.3
    - flatbuffers==2.0
    - freetype-py==2.3.0
    - future==0.18.2
    - gast==0.5.3
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.3
    - h5py==3.7.0
    - idna==3.3
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.7
    - imgaug==0.4.0
    - importlib-metadata==4.11.4
    - importlib-resources==5.7.1
    - ipykernel==6.13.0
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.5.1
    - jupyter-client==7.2.0
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - lmdb==1.1.1
    - lpips==0.1.3
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.2.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - moviepy==1.0.3
    - mrcfile==1.3.0
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - notebook==6.4.11
    - numpy==1.21.6
    - oauthlib==3.2.0
    - onnx==1.11.0
    - onnxruntime==1.11.1
    - open3d==0.11.2
    - opencv-python==4.4.0.44
    - packaging==21.3
    - pandas==1.1.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.0.0
    - plotly==4.9.0
    - plyfile==0.7.4
    - proglog==0.1.10
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyglet==1.5.26
    - pygments==2.12.0
    - pyopengl==3.1.0
    - pyparsing==3.0.9
    - pyrender==0.1.45
    - pyrsistent==0.18.1
    - python-dateutil==2.8.1
    - pytorch-fid==0.1.1
    - pytz==2022.1
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - pyzmq==23.0.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - retrying==1.3.3
    - rsa==4.8
    - scenepic==1.0.7
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - scikit-video==1.1.11
    - scipy==1.7.3
    - send2trash==1.8.0
    - shapely==1.8.2
    - six==1.16.0
    - sk-video==1.1.10
    - sklearn==0.0
    - soupsieve==2.3.2.post1
    - tb-nightly==2.10.0a20220529
    - tensorboard==1.14.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.2
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.1.1
    - torch==1.11.0
    - torch-ema==0.2
    - torch-fidelity==0.2.0
    - torchvision==0.12.0
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.2.1.post0
    - transformations==2021.6.6
    - trimesh==3.12.5
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - validators==0.19.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.1.2
    - widgetsnbextension==3.6.0
    - wrapt==1.14.1
    - yapf==0.32.0
    - zipp==3.1.0
